apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-microservice
  template:
    metadata:
      labels:
        app: sample-microservice
    spec:
      containers:
      - name: sample-microservice
        image: your-docker-registry/sample-microservice:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: sample-microservice-service
spec:
  type: LoadBalancer
  selector:
    app: sample-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081